spring:
  data:
    redis:
      host: "localhost"
      port: 6379
      database: 0
      #      username: root
      password: 1234
      connect-timeout: 5s
      timeout: 5s
      # Lettuce
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms